## Configuracion de Spring
spring:
  application:
    name: ms-books-payments
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:5432/catalogue
    username: ${DATABASE_USERNAME:books}
    password: ${DATABASE_PASSWORD:books123}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

## Configuracion de Instancia 
server:
  port: 8089

gateway:
  url: ${GATEWAY_URL:http://localhost:8762}

## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-books-payments
